id: math-adv-004
brief: 集合并集元素个数计算
category: math
difficulty: advanced
scoring_std:
  max_score: 10
  indicators:
    - accuracy       # 答案正确性
    - completeness   # 解题过程完整性
    - depth          # 方法深度
