id: math-adv-006
brief: 函数奇偶性求最大值
category: math
difficulty: advanced
scoring_std:
  max_score: 10
  indicators:
    - accuracy       # 答案正确性
    - completeness   # 解题过程完整性
    - depth          # 方法深度
