id: math-adv-009
brief: 单位向量点积取整求模
category: math
difficulty: advanced
scoring_std:
  max_score: 10
  indicators:
    - accuracy       # 答案正确性
    - completeness   # 解题过程完整性
    - depth          # 方法深度
