id: math-final-001
brief: 射影直线上层的形变函子是否 miniversal
category: math
difficulty: final
scoring_std:
  max_score: 10
  indicators:
    - accuracy       # 答案正确性
    - completeness   # 论证完整性
    - depth          # 理论深度
