id: math-adv-011
brief: 点集中点坐标问题
category: math
difficulty: advanced
scoring_std:
  max_score: 16
  indicators:
    - accuracy       # 答案正确性
    - completeness   # 解题过程完整性
    - depth          # 方法深度
